name: Trigger the 'cypresstests' Test Workflow on Testkube

on:
  pull_request:
    branches: [ master ]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: kubeshop/setup-testkube@v1
      with:
        organization: ${{ secrets.TK_ORG }}
        environment: ${{ secrets.TK_ENV }}
        token: ${{ secrets.TK_API_TOKEN }}
    - run: |
        testkube run testworkflow cypresstests -f
